version: "3.4"

services:
  identity-server:
    build:
      context: ./IdentityServer
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=IdentityDb;User=sa;Password=htdungP@$$w0rd;

  angular-spa:
    build:
      context: ./angular-spa
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - identity-server
    environment:
      - NODE_ENV=production

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    restart: always
    environment:
      SA_PASSWORD: "htdungP@$$w0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
